services:
  - type: web
    name: project-management
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    releaseCommand: python manage.py migrate --noinput
    startCommand: gunicorn project_management.wsgi --bind 0.0.0.0:$PORT --workers 3 --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        value: ""
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DATABASE_URL
        value: ""
      - key: REDIS_URL
        value: ""
      - key: DJANGO_ALLOWED_HOSTS
        value: ""
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: ""
